"""Catalog index links and ZZ_TARGET_INDEX.md: a port of reference/scripts/make_index_links.py.

    100-ByMessierNumber/M031-AndromedaGalaxy -> ../AndromedaGalaxy-M31
    101-ByNGCNumber/NGC0224-AndromedaGalaxy  -> ../AndromedaGalaxy-M31
    102-ByICNumber/IC1805-HeartNebula        -> ../HeartNebula-IC1805
    103-ByDate/<session folder>              -> ../<Target>/<session folder>

Relative links only (they resolve on the server, so over NFS and SMB). wanted() is pure; apply() touches only
symlinks inside the four index folders (never follows or removes anything else) and rewrites ZZ_TARGET_INDEX.md.
"""

from __future__ import annotations

import csv
import os
from pathlib import Path


DIRS = {"messier": ("100-ByMessierNumber", "M", 3), "ngc": ("101-ByNGCNumber", "NGC", 4), "ic": ("102-ByICNumber", "IC", 4)}
BYDATE = "103-ByDate"
INDEX_MD = "ZZ_TARGET_INDEX.md"
TARGETS_CSV = Path("Z95-ClaudeReferences") / "targets.csv"


def read_rows(root: Path) -> list[dict]:
    with open(Path(root) / TARGETS_CSV, newline="") as f:
        return list(csv.DictReader(f))


def wanted(root: Path, rows: list[dict]) -> dict[str, str]:
    """{link path relative to root: relative target} for every catalog number and every session."""
    root = Path(root)
    want: dict[str, str] = {}
    for r in rows:
        if not (root / r["folder"]).is_dir():
            continue
        for col, (d, pre, width) in DIRS.items():
            for n in filter(None, (r.get(col) or "").split(";")):
                want[f"{d}/{pre}{int(n):0{width}d}-{r['name']}"] = "../" + r["folder"]
    for r in rows:
        t = r["folder"]
        if not (root / t).is_dir():
            continue
        for sname in sorted(os.listdir(root / t)):
            sp = root / t / sname
            if sp.is_dir() and not sp.is_symlink() and sname[:4].isdigit() and sname not in ("_to_delete", "stacked"):
                want[f"{BYDATE}/{sname}"] = f"../{t}/{sname}"
    return want


def index_markdown(rows: list[dict]) -> str:
    lines = ["# Target Index", "", "Generated by astro-ingest (catalog step) from `Z95-ClaudeReferences/targets.csv`.", "",
             "| Target folder | Messier | NGC | IC | Other |", "|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: r["folder"]):
        lines.append(
            f"| `{r['folder']}` | {', '.join('M' + x for x in r['messier'].split(';') if x)} | "
            f"{', '.join('NGC ' + x for x in r['ngc'].split(';') if x)} | "
            f"{', '.join('IC ' + x for x in r['ic'].split(';') if x)} | {r['other']} |")
    return "\n".join(lines) + "\n"


def diff(root: Path, want: dict[str, str]) -> tuple[list[str], list[str]]:
    """(links to add, links to remove) to make the index folders match `want`."""
    root = Path(root)
    remove, have = [], set()
    for d in [v[0] for v in DIRS.values()] + [BYDATE]:
        folder = root / d
        if not folder.is_dir():
            continue
        for x in sorted(os.listdir(folder)):
            p = folder / x
            rel = f"{d}/{x}"
            if p.is_symlink():
                if rel not in want or os.readlink(p) != want[rel]:
                    remove.append(rel)
                else:
                    have.add(rel)
    add = sorted(k for k in want if k not in have)
    return add, remove

