"""The only code that writes to the Astronomy share.

Rules (CLAUDE.md): never overwrite (a clash is skipped and reported), never delete inside the share (a damaged copy
is retired to `_to_delete/` in its own folder), write `<name>.part` then rename, never create dotfiles
(.DS_Store, ._*), verify every copy by checksum, and only one writer at a time (STATE_DIR/ingest.lock).
"""

from __future__ import annotations

import errno
import hashlib
import json
import os
import socket
import time
from pathlib import Path
from typing import Callable

from astro_ingest.config import Config

CHUNK = 4 << 20
STALE_LOCK_S = 12 * 3600


class LockHeld(Exception):
    pass


class WriteLock:
    """STATE_DIR/ingest.lock, created with O_EXCL (works on the shfs mount, unlike flock). Records who holds it;
    a lock whose process is gone (same host) or that is older than 12 h is treated as stale and replaced."""

    def __init__(self, cfg: Config, holder: str):
        self.path = Path(cfg.state_dir) / "ingest.lock"
        self.cfg, self.holder = cfg, holder

    def __enter__(self):
        self.cfg.check_writable(self.path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        for _ in range(2):
            try:
                fd = os.open(self.path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o644)
            except FileExistsError:
                if self._stale():
                    self.path.unlink(missing_ok=True)
                    continue
                raise LockHeld(f"another writer holds {self.path}: {self.path.read_text().strip()}") from None
            with os.fdopen(fd, "w") as f:
                json.dump({"holder": self.holder, "pid": os.getpid(), "host": socket.gethostname(),
                           "since": time.time()}, f)
            return self
        raise LockHeld(f"could not take {self.path}")

    def _stale(self) -> bool:
        try:
            info = json.loads(self.path.read_text())
        except (OSError, ValueError):
            return True
        if time.time() - info.get("since", 0) > STALE_LOCK_S:
            return True
        if info.get("host") == socket.gethostname():
            try:
                os.kill(info["pid"], 0)
            except ProcessLookupError:
                return True
            except PermissionError:
                return False
        return False

    def __exit__(self, *exc):
        self.path.unlink(missing_ok=True)


# The only dotfiles the Organization Guide sanctions (session notes, and the marker for borrowed flats)
SANCTIONED_DOTFILES = frozenset({".project_notes.txt", ".flats_are_copies"})
# Files regenerated by design (replaced in place, never hand-edited)
GENERATED = frozenset({"PROJECT_INFO.txt", "ZZ_TARGET_INDEX.md"})
INDEX_FOLDERS = ("100-ByMessierNumber", "101-ByNGCNumber", "102-ByICNumber", "103-ByDate")


def _check_name(rel: str) -> None:
    parts = rel.split("/")
    for i, part in enumerate(parts):
        last = i == len(parts) - 1
        if not part or part in (".", "..") or (part.startswith(".") and not (last and part in SANCTIONED_DOTFILES)):
            raise ValueError(f"refusing to write a dotfile or odd path: {rel}")


def hash_file(path: Path) -> str:
    h = hashlib.blake2b()
    with open(path, "rb") as f:
        while chunk := f.read(CHUNK):
            h.update(chunk)
    return h.hexdigest()


# Quick check (Chris, 2026-09-27: "Option 2 with option 1 as a Thorough choice"): the size, the first 16 KB (the FITS
# header: capture time, exposure, gain, temperature) and 8 slices of 64 KB spread through the image, hashed together.
# About 0.5 MB read per frame instead of all of it, on the device's Wi-Fi and on the NAS alike. Stored as "quick:<hex>"
# so it can never be mistaken for a full BLAKE2b.
QUICK_HEAD = 16 << 10
QUICK_SLICE = 64 << 10
QUICK_SLICES = 8
QUICK_PREFIX = "quick:"


def quick_offsets(size: int) -> list[tuple[int, int]]:
    """(offset, length) of every piece the quick check reads, for a file of `size` bytes."""
    if size <= QUICK_HEAD + QUICK_SLICES * QUICK_SLICE:
        return [(0, size)]
    span = size - QUICK_HEAD - QUICK_SLICE
    return [(0, QUICK_HEAD)] + [(QUICK_HEAD + span * i // (QUICK_SLICES - 1), QUICK_SLICE) for i in range(QUICK_SLICES)]


def quick_digest(fh, size: int, on_bytes=None) -> str:
    """The quick-check digest of an open (seekable) file of `size` bytes."""
    h = hashlib.blake2b()
    h.update(str(size).encode() + b"\0")
    for off, n in quick_offsets(size):
        fh.seek(off)
        data = fh.read(n)
        if len(data) != n:
            raise OSError(f"short read at {off}: {len(data)} of {n} bytes")
        h.update(data)
        if on_bytes:
            on_bytes(n)
    return QUICK_PREFIX + h.hexdigest()


def digest_matches(path: Path, digest: str) -> bool:
    """Does the file at `path` have this digest (a full BLAKE2b, or a quick-check digest)?"""
    if digest.startswith(QUICK_PREFIX):
        size = path.stat().st_size
        with open(path, "rb") as f:
            try:
                return quick_digest(f, size) == digest
            except OSError:
                return False
    return hash_file(path) == digest


def nas_path(cfg: Config, rel: str) -> Path | None:
    """Where a NAS file is (dev: the sandbox first, then the read-only live share), or None. Never a symlink."""
    for root in (Path(cfg.astro_root), Path(cfg.astro_nas)):
        p = root / rel
        if p.is_file() and not p.is_symlink():
            return p
    return None


def count_files(folder: Path) -> int:
    """Regular files directly in `folder` (ignoring .part leftovers), 0 if it doesn't exist."""
    try:
        return sum(1 for e in os.scandir(folder) if e.is_file(follow_symlinks=False) and not e.name.endswith(".part"))
    except FileNotFoundError:
        return 0


def copy_verified(cfg: Config, staged: Path, dst_rel: str, size: int, blake2b: str,
                  on_bytes: Callable[[int], None] | None = None) -> tuple[str, str]:
    """Copy a staged file to ASTRO_ROOT/dst_rel, verified against its staging hash.

    Returns (status, detail): "done", "already-there" (same size and hash: a harmless rerun), "clash" (something
    else is there: never overwritten) or "failed".
    """
    _check_name(dst_rel)
    dst = Path(cfg.astro_root) / dst_rel
    cfg.check_writable(dst)
    if os.path.lexists(dst):
        if dst.is_file() and not dst.is_symlink() and dst.stat().st_size == size and hash_file(dst) == blake2b:
            return "already-there", "identical file already in place"
        return "clash", "a different file already has this name; not overwritten"
    dst.parent.mkdir(parents=True, exist_ok=True)
    part = dst.with_name(dst.name + ".part")
    part.unlink(missing_ok=True)  # a leftover from an interrupted run
    try:
        with open(staged, "rb") as src, open(part, "xb") as out:
            while chunk := src.read(CHUNK):
                out.write(chunk)
                if on_bytes:
                    on_bytes(len(chunk))
            out.flush()
            os.fsync(out.fileno())
        # verify what actually landed on disk, not what was in memory
        h = hash_file(part)
        if h != blake2b or part.stat().st_size != size:
            part.unlink(missing_ok=True)
            return "failed", "the copy on disk doesn't match the staging checksum"
        _rename_no_clobber(part, dst)
    except FileExistsError:
        part.unlink(missing_ok=True)
        return "clash", "a file appeared at the destination during the copy; not overwritten"
    except OSError as exc:
        part.unlink(missing_ok=True)
        return "failed", f"{type(exc).__name__}: {exc}"
    if dst.stat().st_size != size:
        return "failed", "size changed after rename"
    return "done", "copied and verified"


def _rename_no_clobber(part: Path, dst: Path) -> None:
    """Atomic and never overwrites: hard-link the .part to its final name (fails if the name exists), then remove the
    .part. Shares without hard links fall back to check-then-rename, safe under the single-writer lock."""
    try:
        os.link(part, dst)
    except FileExistsError:
        raise
    except OSError as exc:
        if exc.errno not in (errno.EPERM, errno.ENOTSUP, errno.EXDEV, errno.EMLINK, errno.EOPNOTSUPP):
            raise
        if os.path.lexists(dst):
            raise FileExistsError(dst) from exc
        os.rename(part, dst)
        return
    part.unlink()


def retire(cfg: Config, rel: str) -> tuple[str, str]:
    """Move ASTRO_ROOT/rel into `_to_delete/` in its own folder (never delete, never overwrite)."""
    _check_name(rel)
    src = Path(cfg.astro_root) / rel
    if not os.path.lexists(src):
        return "skipped", "not in the write root (nothing to retire there)"
    dst = src.parent / "_to_delete" / src.name
    cfg.check_writable(dst)
    if os.path.lexists(dst):
        return "clash", f"{dst.parent.name}/{dst.name} already exists; not overwritten"
    dst.parent.mkdir(exist_ok=True)
    os.rename(src, dst)
    return "done", f"retired to {dst.parent.name}/"


def _write_atomic(path: Path, text: str) -> None:
    part = path.with_name(path.name + ".part")
    part.unlink(missing_ok=True)
    with open(part, "x", encoding="utf-8") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(part, path)


def write_generated(cfg: Config, rel: str, text: str) -> str:
    """Write a regenerated file (PROJECT_INFO.txt, ZZ_TARGET_INDEX.md) in place. Returns created/updated/unchanged."""
    _check_name(rel)
    if Path(rel).name not in GENERATED:
        raise ValueError(f"not a generated file: {rel}")
    path = Path(cfg.astro_root) / rel
    cfg.check_writable(path)
    if path.is_file() and path.read_text(encoding="utf-8", errors="replace") == text:
        return "unchanged"
    existed = path.is_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(path, text)
    return "updated" if existed else "created"


def append_lines(cfg: Config, rel: str, lines: list[str], existing: str | None = None) -> str:
    """Add lines to a notes file (.project_notes.txt): what's there is never edited. `existing` is the current text
    when the file only exists on the read-only NAS copy (dev); normally it's read from the write root."""
    _check_name(rel)
    path = Path(cfg.astro_root) / rel
    cfg.check_writable(path)
    current = path.read_text(encoding="utf-8") if path.is_file() else (existing or "")
    new = current.rstrip("\n") + ("\n" if current.strip() else "") + "\n".join(lines) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(path, new)
    return "updated" if current else "created"


def write_new(cfg: Config, rel: str, text: str) -> str:
    """Create a file that must not exist yet (e.g. .flats_are_copies). Returns created or clash."""
    _check_name(rel)
    path = Path(cfg.astro_root) / rel
    cfg.check_writable(path)
    if os.path.lexists(path):
        return "clash"
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(path, text)
    return "created"


def replace_source_file(cfg: Config, rel: str, text: str, stamp: str) -> str:
    """Rewrite a hand-kept source file (targets.csv): the previous version is retired first to
    <folder>/_to_delete/<name>.<stamp>, never deleted or overwritten."""
    _check_name(rel)
    path = Path(cfg.astro_root) / rel
    cfg.check_writable(path)
    if path.is_file():
        if path.read_text(encoding="utf-8") == text:
            return "unchanged"
        old = path.parent / "_to_delete" / f"{path.name}.{stamp}"
        cfg.check_writable(old)
        if os.path.lexists(old):
            return "clash"
        old.parent.mkdir(exist_ok=True)
        os.rename(path, old)
    path.parent.mkdir(parents=True, exist_ok=True)
    _write_atomic(path, text)
    return "updated"


def add_link(cfg: Config, rel: str, target: str) -> str:
    """Create a relative symlink inside one of the index folders (100-…103-)."""
    _check_name(rel)
    if rel.split("/")[0] not in INDEX_FOLDERS or target.startswith("/"):
        raise ValueError(f"index links live in {INDEX_FOLDERS} and are relative: {rel} -> {target}")
    path = Path(cfg.astro_root) / rel
    cfg.check_writable(path.parent)
    if os.path.lexists(path):
        return "clash"
    path.parent.mkdir(parents=True, exist_ok=True)
    os.symlink(target, path)
    return "created"


def remove_link(cfg: Config, rel: str) -> str:
    """Remove a stale symlink inside an index folder (links are generated; nothing else is ever removed here)."""
    if rel.split("/")[0] not in INDEX_FOLDERS:
        raise ValueError(f"not in an index folder: {rel}")
    path = Path(cfg.astro_root) / rel
    cfg.check_writable(path.parent)
    if not path.is_symlink():
        return "skipped"
    path.unlink()
    return "removed"
