# Rebuild catalog index folders from Z95-ClaudeReferences/targets.csv using RELATIVE symlinks:
#   100-ByMessierNumber/M031-AndromedaGalaxy -> ../AndromedaGalaxy-M31
#   101-ByNGCNumber/NGC0224-AndromedaGalaxy  -> ../AndromedaGalaxy-M31
#   102-ByICNumber/IC1805-HeartNebula        -> ../HeartNebula-IC1805
#   103-ByDate/2026-09-13-ElephantTrunkNebula-2600MC-Z61 -> ../ElephantTrunkNebula-IC1396/2026-09-13-ElephantTrunkNebula-2600MC-Z61
# Only touches symlinks inside those three folders; never follows or deletes anything else. Also writes ZZ_TARGET_INDEX.md.
import os,csv
HERE=os.path.dirname(os.path.abspath(__file__)); ROOT=os.path.dirname(os.path.dirname(HERE)); os.chdir(ROOT)
DIRS={'messier':('100-ByMessierNumber','M',3),'ngc':('101-ByNGCNumber','NGC',4),'ic':('102-ByICNumber','IC',4)}
rows=list(csv.DictReader(open(os.path.join(os.path.dirname(HERE),'targets.csv'))))
want={}
for r in rows:
    if not os.path.isdir(r['folder']): print('WARN missing target folder',r['folder']); continue
    for col,(d,pre,w) in DIRS.items():
        for n in filter(None,r[col].split(';')):
            want[os.path.join(d,f"{pre}{int(n):0{w}d}-{r['name']}")]='../'+r['folder']
# 103-ByDate: one link per session (night), named exactly like the session folder (starts with YYYY-MM-DD, so it sorts by date)
BYDATE='103-ByDate'
for r in rows:
    t=r['folder']
    if not os.path.isdir(t): continue
    for sname in os.listdir(t):
        sp=os.path.join(t,sname)
        if os.path.isdir(sp) and not os.path.islink(sp) and sname[:4].isdigit() and sname not in ('_to_delete','stacked'):
            want[os.path.join(BYDATE,sname)]='../'+t+'/'+sname
DIRS2=list(DIRS.values())+[(BYDATE,'',0)]
for d,_,_ in DIRS2:
    os.makedirs(d,exist_ok=True)
    for x in os.listdir(d):
        p=os.path.join(d,x)
        if os.path.islink(p) and (p not in want or os.readlink(p)!=want[p]): os.unlink(p)
made=0
for p,t in sorted(want.items()):
    if not os.path.lexists(p): os.symlink(t,p); made+=1
print('links wanted',len(want),'created',made)
L=['# Target Index','','Generated by `Z95-ClaudeReferences/scripts/make_index_links.py` from `Z95-ClaudeReferences/targets.csv`.','',
   '| Target folder | Messier | NGC | IC | Other |','|---|---|---|---|---|']
for r in sorted(rows,key=lambda r:r['folder']):
    L.append(f"| `{r['folder']}` | {', '.join('M'+x for x in r['messier'].split(';') if x)} | {', '.join('NGC '+x for x in r['ngc'].split(';') if x)} | {', '.join('IC '+x for x in r['ic'].split(';') if x)} | {r['other']} |")
open('ZZ_TARGET_INDEX.md','w').write('\n'.join(L)+'\n')
